[project]
name = "address-matching-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.1",
    "django-bootstrap4>=25.1",
    "django-htmx>=1.23.0",
]
